### ISSUE TITLE
dind container does not start sometimes

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/validator-short-read-assembler#19]
When I run the command 

sudo docker run  --rm --privileged -e IMAGE=velvet -e TASK=default -v /home/belmann/projects/velvet:/build  validator

It often happens that the container does not start and just outputs:

time="2015-04-15T16:22:55Z" level="info" msg="+job serveapi(unix:///var/run/docker.sock)" 
time="2015-04-15T16:22:55Z" level="info" msg="+job init_networkdriver()" 
Sending build context to Docker daemon 
time="2015-04-15T16:22:55Z" level="fatal" msg="Post http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=velvet: dial unix /var/run/docker.sock: no such file or directory"

**Comment by michaelbarton** [comment]
This is a problem if this keeps happening regularly. I don't think DinD has
much official support from Docker. I've discussed some of these issues in -
bioboxes/rfc#120.

**Comment by michaelbarton** [comment]
As of bioboxes/rfc#120 we no longer use DinD.
