### ISSUE TITLE
How to set up circle ci for running this validator

### ISSUE THREAD

**Issue by pbelmann** [bioboxes/validator-short-read-assembler#7]
Add a description to readme.md that clarifies how to setup circleci in order to run this validator on my own assembler biobox.

**Comment by michaelbarton** [comment]
Currently it looks like we have to use the `--privileged` flag to run docker in docker.

http://stackoverflow.com/questions/29612463/can-i-run-docker-in-docker-without-using-the-privileged-flag

**Comment by michaelbarton** [comment]
I can't see a way to currently run the validator on circle while the `--privileged` flag is required. I've created to address some of the problems with the current version of the validator - bioboxes/rfc#120.

**Comment by michaelbarton** [comment]
I believe this is now resolved by #120. The short read assembler validator now works on circleci.
